# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: bkseastone
subtitle: ''
description: 'wangweisong blog'
keywords: 'wangweisong,Hexo,Hexo主题,Blog,博客'
author: wangweisong
language: zh-CN
timezone: ''
#avatar: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/avatar/avatar.png

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://bkseastone.github.io/
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - manifest.json
  - start
  - CNAME
  - robots.txt
  - assets/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis
# 覆盖主题配置
theme_config:
  search:
    enable: true
    service: hexo  # hexo, google, algolia, azure, baidu
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.6.4/js/search.js
  style:
    navbar:
      height: 64px
      effect: [shadow] # [shadow, floatable, blur]
    scrollbar:
      size: 4px
      border: 2px
      color: '#2196f3'
      hover: '#ff5722'
    sidebar:
      effect: [shadow] # [shadow, floatable, blur]
    body:
      effect: [shadow] # [shadow, floatable, blur]
      highlight:
        language: true # show language of codeblock
        copy_btn: true
      text_align: # left, right, justify, center
        h1: left
        h2: left
        h3: left
        h4: left
        p: justify
      note: # style for default note: {% note text %}
        icon: '\f054'
        color: ''
    gap:
      h1: 16px
      h2: 14px # Spacing above H2 (only px unit)
      h3: 12px # Spacing above H3 (only px unit)
      h4: 8px # Spacing above H4 (only px unit)
      #paragraph: 1rem # Paragraph spacing between paragraphs
      #row: .5rem # Paragraph spacing between other elements
      #line_height: 1.65 # normal, 1.5, 1.75, 2 ...
    #color:
    #  site_footer: '#fff'
    #  site: '#21232F' # Website background color
    #  card: '#444' # Card background color
    #  text: '#fff' # The color of the text on the card.
    #  theme: '#ff9800' # Main color
    #  link: '#1BCDFC' # Link color
    #  hover: '#ff5722' # Link highlight color
    #  inner: '#333' # Text color inside the button
    #  block: '#555' # Block color
    #  inlinecode: yellow # Inline code color
    #  codeblock: '#555' # Codeblock color
    #  p: '#ccc' # Paragraph color
    fontfamily:
      logofont:
        fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
        name: 'Varela Round'
        url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
        weight: normal
        style: normal
      bodyfont:
        fontfamily: 'UbuntuMono, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
        name: 'UbuntuMono'
        url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/UbuntuMono/UbuntuMono-Regular.ttf
        weight: normal
        style: normal
      codefont:
        fontfamily: 'Menlo, Monaco'
        name: 'Monaco'
        url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
        weight: normal
        style: normal
  cover:
    scheme: blog # docs, blog
    title: BKSeaStone
    subtitle: ''
    display:
      home: true
      archive: false
      others: false # can be written in front-matter 'cover: true'
    search: 'search index'
    features:
      - name: wiki
        icon: fas fa-book
        url: /
      - name: code
        icon: fas fa-file-code
        url: https://github.com/bkseastone/bkseastone.github.io
        rel: external nofollow noopener noreferrer
        target: _blank
      - name: contributors
        icon: fas fa-handshake
        url: /contributors/
  navbar:
    logo: # choose [img] or [icon + title]
      img:
      icon:
      title: bkseastone$ 
    menu:
      # The following can be written in `blog/source/_data/menu.yml`
      - name: 1
        icon: fas fa-rss
        url: /
      - name: 2
        icon: fas fa-folder-open
        url: categories/
      - name: 3
        icon: fas fa-tags
        url: tags/
      - name: 4
        icon: fas fa-archive
        url: archives/
      - name: 5
        icon: fas fa-link
        url: friends/
      - name: 6
        icon: fas fa-info-circle
        url: about/
      - name: 7
        icon: fas fa-ellipsis-v
        rows:
          - name: 7.1
            url: https://github.com/xaoxuu/hexo-theme-volantis/
          - name: 7.2
            url: https://github.com/xaoxuu/hexo-theme-volantis/releases/
          # 分割线
          - name: hr
          - name: 7.3 >
            rows:
              - name: 7.3.1
                url: faqs/
              - name: 7.3.2
                url: https://github.com/xaoxuu/volantis-docs/
              - name: 7.3.3
                url: https://github.com/xaoxuu/hexo-theme-volantis/issues/
          - name: hr
          - name: 小标题
            icon: fas fa-fire
          - name: 7.4
            url: archives/
          - name: 7.5
            url: examples/
          - name: 7.6
            url: contributors/
    search: search index   # Search bar placeholder
  layout:
    # The following can be written in `blog/source/_data/layout.yml`
    # 文章列表（主页、自定义的列表）布局
    on_list:
      # 列表中每一篇文章的meta信息
      meta: [title, tags, updated, wordcount, top]
      # 列表类页面的侧边栏
      sidebar: [blogger, category, tagcloud]
      # read more button
      readmore: 阅读全文 <i class="fas fa-chevron-right"></i>
    # 页面布局
    on_page:
      # 文章页面主体元素，你也可以在页面的Front-matter中设置
      body: [article, comments]
      # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
      # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
      # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
      meta:
        header: [title, category, date, updated, counter, share]
        footer: [tags, share]
      # 文章页面的侧边栏
      sidebar: [toc, related_posts]
    # 文章布局，参数继承自 on_page
    on_post:
      # 文章页脚，自动在每一篇文章末尾添加
      article_footer: [references, related_repos, copyright, donate]
    # 其他的页面布局暂时等于 on_list
  meta:
    # 文章标题
    title: # 暂无配置
    author:
      name: wangweisong
      avatar: 
      url: https://github.com/bkseastone
    # 文章创建日期
    date:
      icon: fas fa-calendar-alt
      title: '发布于：'
      format: 'll' # 日期格式 http://momentjs.com/docs/
    # 文章更新日期
    updated:
      icon: fas fa-edit
      title: '更新于：'
      format: 'll' # 日期格式 http://momentjs.com/docs/
    # 文章分类
    category:
      icon: fas fa-folder-open
    # 文章置顶
    top:
      icon: fas fa-angle-double-up
    # 文章浏览计数
    counter:
      icon: fas fa-eye
    # 文章字数和阅读时长
    wordcount:
      icon_wordcount: fas fa-keyboard
      icon_duration: fas fa-hourglass-half
    # 文章标签
    tags:
      icon: fas fa-hashtag
    # 分享
    share:
      - id: qq
        img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qq.png
      - id: weibo
        img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png
      - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
        img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/wechat.png
      - id: telegram
        img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/telegram.png
    # 链接
    btns:
      edit:
        icon: fas fa-edit
        title: 在GitHub上编辑此页
        color: '#888'
      repo: # 源码链接
        icon: fas fa-file-code
        title: 源码
        color: '#508EF2'
      bug: # BUG反馈链接
        icon: fas fa-bug
        title: BUG
        color: '#FE5F58'
      doubt: # 疑问链接
        icon: fas fa-question-circle
        title: 疑问
        color: '#FFBD2B'
      idea: # 建议链接
        icon: fas fa-lightbulb
        title: 建议
        color: '#3DC550'
      faq: # FAQ链接
        icon: fas fa-comments
        title: FAQ
        color: '#29B1C9'
      feedback: # 反馈链接
        icon: fas fa-comment-dots
        title: 反馈
        color: '#1BCDFC'
  widget:
    # The following can be written in `blog/source/_data/widget.yml`
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: 
      title:
      subtitle:
      jinrishici: 不主动的都算不得念旧之人 # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: cat
      list_number: true
      min_depth: 2
      max_depth: 5
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: folder
        url: /categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: hot tags
        url: /tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'
    # ---------------------------------------
    # related posts widget
    related_posts:
      class: related_posts # npm i -S hexo-related-popular-posts
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-bookmark
        title: related posts
      max_count: 5
    # ---------------------------------------
    # copyright widget (valid only in articles)
    copyright:
      class: copyright
      display: [desktop, mobile] # [desktop, mobile]
      blockquote: true
      permalink: '本文永久链接是：'
      content:
        - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
        - permalink
    # ---------------------------------------
    # qrcode widget
    donate:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: 64px  # Automatic height if not set
      fancybox: true
      images:
        - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
    repos:
      class: text
      display: [desktop] # [desktop, mobile]
      header:
        icon: fab fa-github
        title: 点个赞吧
        url: https://github.com/bkseastone/
      content:
        - '您的赞对我来说很重要，如果您喜欢本主题，希望能够给下面的项目点个赞来支持一下。'
        - '[<img src="https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/proj/prohud/logo.png" height="50px">](https://github.com/bkseastone)'
        - '[<img src="https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/proj/valuex/logo.png" height="50px">](https://github.com/bkseastone)'
        - '[<img src="https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/proj/inspire/logo.png" height="50px">](https://github.com/bkseastone)'

    wiki-hexo-theme:
      class: list
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-chevron-left
        title: Hexo Themes
        url: /wiki/
      rows:
        - name: Volantis for Hexo
          url: /wiki/volantis/
        - name: Resume for Hexo
          url: /wiki/resume/
    # front-matter
    # references:
    #   - name: Apple Developer Documentation
    #     url: https://developer.apple.com/documentation/
    references:
      class: references # is subclass of list
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-quote-left
        title: 参考资料
    # front-matter
    # group: group-1
    # order: 16
    # sidebar: [group-1, toc]
    group-1:
      class: group
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fab fa-apple
        title: Developer
        url: /wiki/ios/

  seo:
    # When there are no keywords in the article's front-matter, use tags as keywords.
    use_tags_as_keywords: true
    # When there is no description in the article's front-matter, use excerpt as the description.
    use_excerpt_as_description: true
    robots:
      home_first_page: index,follow
      home_other_pages: noindex,follow
      archive: noindex,follow
      category: noindex,follow
      tag: noindex,follow
      # robots can be written in front-matter

  comments:
    title: <i class='fas fa-comments'></i> 用户交流区
    subtitle:
    service: gitalk  # valine, minivaline, disqus, gitalk, livere
    # 可以通过设置 gitalk.id 实现多个页面共用一个评论框
    # front-matter
    # gitalk:
    #   id: /wiki/volantis/
    gitalk:
      clientID: 631927553dae1549fdb6
      clientSecret: e3007743ce92f91c63d50d4fc292593abb23b826
      repo: bkseastone.github.io
      owner: bkseastone
      admin: [bkseastone]

  footer:
    # layout of footer: [aplayer, social, license, info, copyright]
    layout: [social, license, br, info, copyright]
    social:
      - icon: fas fa-envelope
        url: mailto:872883039@qq.com
      - icon: fab fa-github
        url: https://github.com/bkseastone
    copyright: '[Copyright © 2017-2020 wangweisong](https://bkseastone.github.io)'
    # You can add your own property here. (Support markdown, for example: br: '<br>')
    br: '<br>'

  plugins:
    ######## Plugins to improve loading speed:
    # Preload (The menu's url must end with ‘/’)
    instant_page: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/instant_page.js
    comment_typing: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/comment_typing.js
      # https://scrollrevealjs.org/api/reveal.html
    scrollreveal:
      js: https://cdn.jsdelivr.net/npm/scrollreveal@4.0.6/dist/scrollreveal.min.js
      distance: 8px
      duration: 800 # ms
      interval: 100 # ms
      scale: 1 # 0.1~1

    # Codeblock Copy Button
    clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

    ######## Plugins for SEO:
    # Traffic statistics (very slow loading)
    busuanzi: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js

    # npm i --save hexo-wordcount
    wordcount: true

    ######## Plugins for ...
    # Button Ripple Effect
    nodewaves:
      css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
      js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

    backstretch:
      enable: true
      js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
      position: cover  # cover: sticky on the cover.   fixed: Fixed as background for the site.
      shuffle: true  
      duration: 20000       # Duration (ms)
      fade: 1500            # fade duration (ms) (Not more than 1500)
      images:               # For personal use only. At your own risk if used for commercial purposes !!!
        - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/41F215B9-261F-48B4-80B5-4E86E165259E.jpeg
    aplayer:
      enable: false
      js:
        - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
        - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
      # Required
      server: netease   # netease, tencent, kugou, xiami, baidu
      type: search    # song, playlist, album, search, artist
      id: 追光者    # song id / playlist id / album id / search keyword
      # Optional
      fixed: false      # enable fixed mode
      theme: '#1BCDFC'  # main color
      autoplay: true   # audio autoplay
      order: list       # player play order, values: 'list', 'random'
      loop: all         # player loop play, values: 'all', 'one', 'none'
      volume: 0.2       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
      list_max_height: 340px # list max height
      list_folded: true


# Deployment
## Docs: https://hexo.io/docs/deployment.html
# npm install hexo-deployer-git --save
deploy:
  type: git
  repo: git@github.com:bkseastone/bkseastone.github.io.git
  branch: master
  message: "Github CI Auto Builder at {{ now('YYYY-MM-DD HH:mm:ss Z') }}"

# 全局导入
import:
  meta:
  - "<meta name='theme-color' content='#FFFFFF'>"
  link:
  - "<link rel='shortcut icon' type='image/x-icon' sizes='16x16 32x32 48x48 64x64' href='/assets/favicon/favicon.ico'>"
  - "<link rel='apple-touch-icon' type='image/png' sizes='180x180' href='/assets/favicon/favicon_180.png'>"
  - "<link rel='mask-icon' color='#1BC3FB' href='/assets/favicon/favicon_180.png'>"
  - "<link rel='manifest' href='/manifest.json'>"
  # script:

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false

# 图片懒加载  # hexo-lazyload-image    hexo-fs
lazyload:
  enable: true
  onlypost: false
  loadingImg: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg

# npm install hexo-all-minifier --save
all_minifier: true

# hexo-autonofollow
nofollow:
  enable: true
  exclude:
  - bkseastone.github.io

# autoprefixer
autoprefixer:
  exclude:
  - '*.min.css'

# offline config passed to sw-precache.
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: false
  modifyAnchors: 0
  autolink: true
  sanitizeUrl: false
  headerIds: true
  prependRoot: false
  external_link:
    enable: true
    exclude: []
    nofollow: true
